FROM dorowu/ubuntu-desktop-lxde-vnc
RUN apt update
RUN apt install -Y lib32ncurses5-dev
RUN apt install -y zip
RUN apt install -y gedit
RUN apt install -y gcc
RUN apt install -y gdb
RUN apt install -y make
RUN apt install -y firefox
RUN apt install -y nautilus
